---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages
  apt:
    name:
      - net-tools
      - dnsutils
      - wget
      - curl
      - mc
      - rsync
    state: present
